# Purpose of this project
The purpose of this project is to parse and transform a `CAMT.053` file into a dataframe.
I will not go into each and every tag, for that information you can check one of your banks CAMT implementation guidelines, for example: [ABN](https://www.abnamro.nl/nl/images/Content/022_Zakelijk_nieuwe_structuur/000_Gedeelde_documenten/pdf_sepa_betaalvereniging_ig_camt_v1-0.pdf)

# General information and benefits of CAMT reporting
* CAMT stands for _Cash Management_ and is an [ISO 20022](https://www.iso20022.org/payments_messages.page) (XML) standard globally 
* ISO defines the standards for electronic data exchanges between financial institutions
* ISO also calls it _"Universal financial industry message scheme"_
* Using these standards, it will allow banks and customers to use a standard way of reporting account information globally
* This consistency is essential so customers and system developers can rely on the fact that banks populate the information in a defined manner
* Banks can no longer store account information in their own manner
> * There are specific tags for specific information
> * Only differences can be that not all tags are always present, it depends on the type of transaction if certain tags are populated

--> The end goal is to improve the end to end business process from payments to reconciliation

# File specific information
CAMT.053 files are `.XML` files. Which means the data is stored in layers (or tree structure).
This means it is not as easy to read as tabular data (for example Excel)

To be able to parse this file, first we need to understand its structure.  
The XML tree of each CAMT.053 has the following format:
> Document
>> BkToCstmrStmt
>>> GrpHdr
>>>> Stmt
>>>>> Bal
>>>>> Ntry
>>>>>> NtryDtls
>>>>>>> Btch  
>>>>>>> TxDtls

## CrdtDbtInd
The specifications Balance (Bal), Entry (Ntry) and Batch (Btch) have the tag `CrdtDbtInd`.
This tag has two valid values: `DBIT` (Debit) and `CRDT` (Credit). These tags must be seen from the perspective of the receiving party. So the owner of the file must see a DBIT value as negative and CRDT as positive amount on the balance

### Import modules we need in our project

In [1]:
import xml.etree.ElementTree as ET
import pandas as pd
import numpy as np
import os
from lxml import etree

In [3]:
def searchdirectory_xml():
    camt_files = list()
    
    os.chdir('..\\01_Input')
    
    for file in os.listdir():
        if 'CAMT' in file and not file.endswith('.ipynb'):
            camt_files.append(file)
            
    return camt_files


searchdirectory_xml()

['CAMT053 voorbeeldbestand.xml']

In [4]:
def batchfiles_indicator():

    batch_indicator = dict()

    for file in searchdirectory_xml():
        with open(file) as f:
            data = f.read()
            if 'Btch' in data:
                batch_indicator[file] = True
            else:
                batch_indicator[file] = False
                
    return batch_indicator

batchfiles_indicator()

{'CAMT053 voorbeeldbestand.xml': True}

In [127]:
def parse_getroot(filename):
    tree = etree.parse(filename)
    root = tree.getroot()
    
    #raise error if its not a CAMT file
    if root.tag[32:40] != ('camt.053'):
        raise ValueError('No CAMT.053 file was used as input')
        
    return root, tree

In [139]:
#create a namespace which we need when parsing
def create_namespace(filename):
    root = parse_getroot(filename)
    
    #create namespace
    ns = '{' + root[0].nsmap[None] + '}'
        
    return ns

In [142]:
def create_groupheader(filename):
    
    ns = create_namespace(filename)
    root = parse_getroot(filename)[0]
    
    for x in root.findall(ns + 'BkToCstmrStmt'):
        for nextlevel in x.findall(ns + 'GrpHdr'):
            msgid = nextlevel.find(ns + 'MsgId').text
            credttm = nextlevel.find(ns + 'CreDtTm').text
            #print(nextlevel.getchildren())

            for msg in nextlevel.findall(ns + 'MsgPgntn'):
                pagenum = msg.find(ns + 'PgNb').text
                lastpage = msg.find(ns + 'LastPgInd').text

    groupheader = pd.DataFrame({'FileName' : filename,
                                'MsgId': msgid,
                                'CreDtTm' : credttm,
                                'PgNb' : pagenum,
                                'LastPgInd' : lastpage}, index=[0])

    return groupheader

In [146]:
def create_groupheader_2(filename):
    
    root, camt = parse_getroot(filename)
    ns = root.tag[1:root.tag.index('}')]
    
    msgid = camt.xpath(
        '//ns:GrpHdr/ns:MsgId', namespaces={'ns':ns})[0].text
    
    credttm = camt.xpath(
        '//ns:GrpHdr/ns:CreDtTm', namespaces={'ns':ns})[0].text
    
    pagenum = camt.xpath(
        '//ns:GrpHdr/ns:MsgPgntn/ns:PgNb', namespaces={'ns':ns})[0].text
    
    lastpage = camt.xpath(
        '//ns:GrpHdr/ns:MsgPgntn/ns:LastPgInd', namespaces={'ns':ns})[0].text
    
    groupheader = pd.DataFrame({'FileName' : filename,
                            'MsgId': msgid,
                            'CreDtTm' : credttm,
                            'PgNb' : pagenum,
                            'LastPgInd' : lastpage}, index=[0])
    
    return groupheader

,FileName,MsgId,CreDtTm,PgNb,LastPgInd
0,CAMT053_Example.xml,0574908765.2013-04-02,2013-04-12T10:55:08.66+02:00,1,true

In [144]:
%%timeit
create_groupheader(file)

2.59 ms ± 300 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [147]:
%%timeit
create_groupheader_2(file)

1.85 ms ± 46.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [167]:
def create_statement(filename):
    
    ns = create_namespace(filename)
    root = parse_getroot(filename)[0]
    
    for highestlevel in root.findall(ns + 'BkToCstmrStmt'):
        for statement in highestlevel.findall(ns + 'Stmt'):
            stmtid = statement.find(ns + 'Id').text
            seqnb = statement.find(ns + 'ElctrncSeqNb').text
            credttm = statement.find(ns + 'CreDtTm').text
            for acct in statement.findall(ns + 'Acct'):
                for Id in acct.findall(ns + 'Id'):
                    iban = Id.find(ns + 'IBAN').text
                ccy = acct.find(ns + 'Ccy').text
            for svcr in acct.findall(ns + 'Svcr'):
                for fininstid in svcr.findall(ns + 'FinInstnId'):
                    bic = fininstid.find(ns + 'BIC').text
                    
    
    statement = pd.DataFrame({'FileName' : filename,
                              'Id' : stmtid,
                              'ElctrncSeqNb' : seqnb,
                              'CreDtTm' : credttm,
                              'IBAN' : iban,
                              'Ccy' : ccy,
                              'BIC' : bic}, index=[0])
    
    return statement

In [160]:
def create_statement_2(filename):
    
    root, camt = parse_getroot(filename)
    ns = root.tag[1:root.tag.index('}')]

    stmtid = camt.xpath(
        '//ns:Stmt/ns:Id', namespaces={'ns':ns})[0].text

    seqnb = camt.xpath(
        '//ns:Stmt/ns:ElctrncSeqNb', namespaces={'ns':ns})[0].text

    credttm = camt.xpath(
        '//ns:Stmt/ns:CreDtTm', namespaces={'ns':ns})[0].text

    iban = camt.xpath(
        '//ns:Stmt/ns:Acct/ns:Id/ns:IBAN', namespaces={'ns':ns})[0].text

    ccy = camt.xpath(
        '//ns:Stmt/ns:Acct/ns:Ccy', namespaces={'ns':ns})[0].text

    bic = camt.xpath(
        '//ns:Stmt/ns:Acct/ns:Svcr/ns:FinInstnId/ns:BIC', namespaces={'ns':ns})[0].text

    statement = pd.DataFrame({'FileName' : filename,
                              'Id' : stmtid,
                              'ElctrncSeqNb' : seqnb,
                              'CreDtTm' : credttm,
                              'IBAN' : iban,
                              'Ccy' : ccy,
                              'BIC' : bic}, index=[0])

    return statement

In [168]:
%%timeit
create_statement(file)

2.86 ms ± 187 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [169]:
%%timeit
create_statement_2(file)

1.96 ms ± 81.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [52]:
def create_balance(filename):
 
    ns = create_namespace(file)
    root = parse_getroot(file)[0]

    cdorprtry_cd = list()
    amount_balance = list()
    cdtdbtind = list()
    dt = list()

    for highestlevel in root.findall(ns + 'BkToCstmrStmt'):
        for statement in highestlevel.findall(ns + 'Stmt'):
            for bal in statement.findall(ns + 'Bal'):
                for tp in bal.findall(ns + 'Tp'):
                    for cdorprtry in tp.findall(ns + 'CdOrPrtry'):
                        cdorprtry_cd.append(cdorprtry.find(ns + 'Cd').text)
                amount_balance.append(float(bal.find(ns + 'Amt').text))
                cdtdbtind.append(bal.find(ns + 'CdtDbtInd').text)
                for date in bal.findall(ns + 'Dt'):
                    dt.append(date.find(ns + 'Dt').text)

    balance = pd.DataFrame()

    balance['Cd'] = cdorprtry_cd
    balance['Amt'] = amount_balance
    balance['CdtDbtInd'] = cdtdbtind
    balance['Dt'] = dt
    balance['FileName'] = filename

    return balance

In [14]:
def create_entry(filename):
    
    root = parse_getroot(filename)[0]
    ns = create_namespace(filename)
    
    amount           = list()
    cddbt            = list()
    sts              = list()
    bookgdt          = list()
    valdt            = list()   
    acctsvcrref      = list()
    bktxcd_cd        = list()
    bktxcd_fmlycd    = list()
    bktxcd_subfmlycd = list()
    prtry_cd         = list()
    prtry_issr       = list()
    
    for child in root:
        for layer in child.findall(ns + 'Stmt'):
            for childlayer in layer.findall(ns + 'Ntry'):
                
                amount.append(childlayer.find(ns + 'Amt').text)
                
                cddbt.append(childlayer.find(ns + 'CdtDbtInd').text)
                
                sts.append(childlayer.find(ns + 'Sts').text)
                
                for bookdate in childlayer.findall(ns + 'BookgDt'):
                    bookgdt.append(bookdate.find(ns + 'Dt').text)
                    
                for valdate in childlayer.findall(ns + 'ValDt'):
                    valdt.append(valdate.find(ns + 'Dt').text)
                    
                    
                if childlayer.find(ns + 'AcctSvcrRef') is not None:
                    acctsvcrref.append(childlayer.find(ns + 'AcctSvcrRef').text)
                else:
                    acctsvcrref.append(np.nan)
                    
                for bktxcd in childlayer.findall(ns + 'BkTxCd'):
                    for domain in bktxcd.findall(ns + 'Domn'):
                        bktxcd_cd.append(domain.find(ns + 'Cd').text)
                        
                        for fmlycd in domain.findall(ns + 'Fmly'):
                            bktxcd_fmlycd.append(fmlycd.find(ns + 'Cd').text)
                            bktxcd_subfmlycd.append(fmlycd.find(ns + 'SubFmlyCd').text)
                    for prtry in bktxcd.findall(ns + 'Prtry'):
                        prtry_cd.append(prtry.find(ns + 'Cd').text)
                        prtry_issr.append(prtry.find(ns + 'Issr').text)
                        
    Ntry = pd.DataFrame()
    
    Ntry['Amount'] = amount
    Ntry['CdDbtInd'] = cddbt
    Ntry['Sts'] = sts
    Ntry['BookgDt'] = bookgdt
    Ntry['ValDt'] = valdt
    Ntry['AcctSvcrRef'] = acctsvcrref
    Ntry['BkTxCd_Cd'] = bktxcd_cd
    Ntry['BkTxCd_FmlyCd'] = bktxcd_fmlycd
    Ntry['BkTxCd_SubFmlyCd'] = bktxcd_subfmlycd
    Ntry['Prtry_Cd'] = prtry_cd
    Ntry['FileName'] = filename

    
    return Ntry

In [33]:
all_groupheaders = pd.DataFrame()

for f in searchdirectory_xml():
    df = create_groupheader(f)
    all_groupheaders = all_groupheaders.append(df, ignore_index=True)

all_groupheaders

,FileName,MsgId,CreDtTm,PgNb,LastPgInd
0,CAMT053_Exampe.xml,0574908765.2013-04-02,2013-04-12T10:55:08.66+02:00,1,true
1,CAMT053_Example2.xml,CAMT053JJJJMMTT0000000000000001,JJJJ-MM-TTT00:00:00.1+01:00,1,true
2,CAMT053_Example3.xml,AAAASESS-FP-STAT001,2010-10-18T17:00:00+01:00,1,true

In [16]:
all_statements = pd.DataFrame()

for f in searchdirectory_xml():
    df = create_statement(f)
    all_statements = all_statements.append(df, ignore_index=True)

all_statements

,FileName,Id,ElctrncSeqNb,CreDtTm,IBAN,Ccy,BIC
0,CAMT053 voorbeeldbestand.xml,0574908765.2013-04-02,0070,2013-04-12T10:55:08.66+02:00,NL77ABNA0574908765,EUR,ABNANL2A

In [53]:
all_balances = pd.DataFrame()

for f in searchdirectory_xml():
    df = create_balance(f)
    all_balances = all_balances.append(df)
    
all_balances

     Cd      Amt CdtDbtInd          Dt              FileName
0  PRCD  1000.01      CRDT  2013-03-28   CAMT053_Example.xml
1  CLBD   100.01      CRDT  2013-04-02   CAMT053_Example.xml
2  CLAV   100.01      CRDT  2013-04-02   CAMT053_Example.xml
3  FWAV   100.01      CRDT  2012-04-03   CAMT053_Example.xml
4  FWAV   100.01      CRDT  2012-04-04   CAMT053_Example.xml
5  FWAV   100.01      CRDT  2012-04-05   CAMT053_Example.xml
6  FWAV   100.01      CRDT  2012-04-08   CAMT053_Example.xml
7  FWAV   100.01      CRDT  2012-04-09   CAMT053_Example.xml
0  PRCD  1000.01      CRDT  2013-03-28  CAMT053_Example2.xml
1  CLBD   100.01      CRDT  2013-04-02  CAMT053_Example2.xml
2  CLAV   100.01      CRDT  2013-04-02  CAMT053_Example2.xml
3  FWAV   100.01      CRDT  2012-04-03  CAMT053_Example2.xml
4  FWAV   100.01      CRDT  2012-04-04  CAMT053_Example2.xml
5  FWAV   100.01      CRDT  2012-04-05  CAMT053_Example2.xml
6  FWAV   100.01      CRDT  2012-04-08  CAMT053_Example2.xml
7  FWAV   100.01      CRDT  2012-04-09  CAMT053_Example2.xml
0  PRCD  1000.01      CRDT  2013-03-28  CAMT053_Example3.xml
1  CLBD   100.01      CRDT  2013-04-02  CAMT053_Example3.xml
2  CLAV   100.01      CRDT  2013-04-02  CAMT053_Example3.xml
3  FWAV   100.01      CRDT  2012-04-03  CAMT053_Example3.xml
4  FWAV   100.01      CRDT  2012-04-04  CAMT053_Example3.xml
5  FWAV   100.01      CRDT  2012-04-05  CAMT053_Example3.xml
6  FWAV   100.01      CRDT  2012-04-08  CAMT053_Example3.xml
7  FWAV   100.01      CRDT  2012-04-09  CAMT053_Example3.xml

In [17]:
all_entrys = pd.DataFrame()

for f in searchdirectory_xml():
    df = create_entry(f)
    all_entrys = all_entrys.append(df, ignore_index=True)

# convert the Amount column to numeric so we can make calculations with it    
all_entrys['Amount'] = all_entrys.Amount.astype(float)

# convert the date columns to date type
all_entrys['BookgDt'] = pd.to_datetime(all_entrys.BookgDt, format='%Y-%m-%d')
all_entrys['ValDt'] = pd.to_datetime(all_entrys.ValDt, format='%Y-%m-%d')

all_entrys

,Amount,CdDbtInd,Sts,BookgDt,ValDt,AcctSvcrRef,BkTxCd_Cd,BkTxCd_FmlyCd,BkTxCd_SubFmlyCd,Prtry_Cd,FileName
0,1.0,CRDT,BOOK,2013-04-02,2013-04-02,2102830989503100038,PMNT,RCDT,NTAV,N196,CAMT053 voorbeeldbestand.xml
1,1.0,CRDT,BOOK,2013-04-02,2013-04-02,3095D4322561459S0PS,PMNT,RCDT,ESCT,N654,CAMT053 voorbeeldbestand.xml
2,1.0,CRDT,BOOK,2013-04-02,2013-04-02,3095D4322561460S0PS,PMNT,RCDT,ESCT,N946,CAMT053 voorbeeldbestand.xml
3,10.0,CRDT,BOOK,2013-04-02,2013-04-02,3095D4322561460S0PS,PMNT,RCDT,ESCT,N946,CAMT053 voorbeeldbestand.xml
4,1.0,CRDT,BOOK,2013-04-02,2013-04-02,3922000TRP7K6HAZ0BI,PMNT,RCDT,ESCT,N944,CAMT053 voorbeeldbestand.xml
5,1.0,DBIT,BOOK,2013-04-02,2013-04-02,3088J0537755115S0EC,PMNT,ICDT,ESCT,N658,CAMT053 voorbeeldbestand.xml
6,2.0,DBIT,BOOK,2013-04-02,2013-04-02,3088J0537755115S0EC,PMNT,ICDT,ESCT,N655,CAMT053 voorbeeldbestand.xml
7,2.0,DBIT,BOOK,2013-04-02,2013-04-02,3088J0537755116S0EC,PMNT,ICDT,SALA,N652,CAMT053 voorbeeldbestand.xml
8,1.0,DBIT,BOOK,2013-04-02,2013-04-02,3077K3403606428S0AD,PMNT,RDDT,ESDD,N248,CAMT053 voorbeeldbestand.xml
9,7.0,CRDT,BOOK,2012-04-02,2012-04-02,1402P5518750498B0AO,PMNT,IDDT,ESDD,N247,CAMT053 voorbeeldbestand.xml
10,7.0,CRDT,BOOK,2012-04-02,2012-04-02,1402P5518750498B0AO,PMNT,IDDT,ESDD,N247,CAMT053 voorbeeldbestand.xml
11,1.0,DBIT,BOOK,2012-04-02,2012-04-02,GB020000738195160AO,PMNT,IDDT,UPDD,N246,CAMT053 voorbeeldbestand.xml
12,921.0,DBIT,BOOK,2012-04-02,2012-04-02,GB030000738195160AO,PMNT,IDDT,UPDD,N245,CAMT053 voorbeeldbestand.xml

In [18]:
all_entrys.groupby('FileName').agg({'FileName':'count',
                                    'Amount':'sum'})

                              FileName  Amount
FileName
CAMT053 voorbeeldbestand.xml        13   956.0

In [19]:
all_entrys = all_entrys.merge(all_statements[['IBAN', 'FileName']], left_on = 'FileName', right_on='FileName', how='left')
all_entrys

,Amount,CdDbtInd,Sts,BookgDt,ValDt,AcctSvcrRef,BkTxCd_Cd,BkTxCd_FmlyCd,BkTxCd_SubFmlyCd,Prtry_Cd,FileName,IBAN
0,1.0,CRDT,BOOK,2013-04-02,2013-04-02,2102830989503100038,PMNT,RCDT,NTAV,N196,CAMT053 voorbeeldbestand.xml,NL77ABNA0574908765
1,1.0,CRDT,BOOK,2013-04-02,2013-04-02,3095D4322561459S0PS,PMNT,RCDT,ESCT,N654,CAMT053 voorbeeldbestand.xml,NL77ABNA0574908765
2,1.0,CRDT,BOOK,2013-04-02,2013-04-02,3095D4322561460S0PS,PMNT,RCDT,ESCT,N946,CAMT053 voorbeeldbestand.xml,NL77ABNA0574908765
3,10.0,CRDT,BOOK,2013-04-02,2013-04-02,3095D4322561460S0PS,PMNT,RCDT,ESCT,N946,CAMT053 voorbeeldbestand.xml,NL77ABNA0574908765
4,1.0,CRDT,BOOK,2013-04-02,2013-04-02,3922000TRP7K6HAZ0BI,PMNT,RCDT,ESCT,N944,CAMT053 voorbeeldbestand.xml,NL77ABNA0574908765
5,1.0,DBIT,BOOK,2013-04-02,2013-04-02,3088J0537755115S0EC,PMNT,ICDT,ESCT,N658,CAMT053 voorbeeldbestand.xml,NL77ABNA0574908765
6,2.0,DBIT,BOOK,2013-04-02,2013-04-02,3088J0537755115S0EC,PMNT,ICDT,ESCT,N655,CAMT053 voorbeeldbestand.xml,NL77ABNA0574908765
7,2.0,DBIT,BOOK,2013-04-02,2013-04-02,3088J0537755116S0EC,PMNT,ICDT,SALA,N652,CAMT053 voorbeeldbestand.xml,NL77ABNA0574908765
8,1.0,DBIT,BOOK,2013-04-02,2013-04-02,3077K3403606428S0AD,PMNT,RDDT,ESDD,N248,CAMT053 voorbeeldbestand.xml,NL77ABNA0574908765
9,7.0,CRDT,BOOK,2012-04-02,2012-04-02,1402P5518750498B0AO,PMNT,IDDT,ESDD,N247,CAMT053 voorbeeldbestand.xml,NL77ABNA0574908765
10,7.0,CRDT,BOOK,2012-04-02,2012-04-02,1402P5518750498B0AO,PMNT,IDDT,ESDD,N247,CAMT053 voorbeeldbestand.xml,NL77ABNA0574908765
11,1.0,DBIT,BOOK,2012-04-02,2012-04-02,GB020000738195160AO,PMNT,IDDT,UPDD,N246,CAMT053 voorbeeldbestand.xml,NL77ABNA0574908765
12,921.0,DBIT,BOOK,2012-04-02,2012-04-02,GB030000738195160AO,PMNT,IDDT,UPDD,N245,CAMT053 voorbeeldbestand.xml,NL77ABNA0574908765